# Generated by Django 4.0.3 on 2022-04-01 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientForename', models.CharField(max_length=45)),
                ('clientSurname', models.CharField(max_length=45)),
                ('clientLoginID', models.CharField(max_length=10)),
                ('clientEmail', models.CharField(max_length=145)),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locName', models.CharField(max_length=125)),
                ('locAddressOne', models.CharField(max_length=125)),
                ('locAddressTwo', models.CharField(max_length=125)),
                ('locCity', models.CharField(max_length=35)),
                ('locPostcode', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laptopBrand', models.CharField(max_length=15)),
                ('laptopModel', models.CharField(max_length=25)),
                ('laptopMemory', models.IntegerField()),
                ('laptopLocation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='assets.location')),
                ('laptopUser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='assets.client')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='clientLocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.location'),
        ),
    ]
